; 扩展 ASCII 字符矩形框绘制测试
; 使用 INT 21H AH=02H 绘制各种边框图形

.MODEL SMALL
.STACK 100H

.DATA
    ; 单线框字符
    SINGLE_TOP_LEFT     DB 0DAH  ; ┌
    SINGLE_TOP_RIGHT    DB 0BFH  ; ┐
    SINGLE_BOTTOM_LEFT  DB 0C0H  ; └
    SINGLE_BOTTOM_RIGHT DB 0D9H  ; ┘
    SINGLE_HORIZONTAL   DB 0C4H  ; ─
    SINGLE_VERTICAL     DB 0B3H  ; │
    
    ; 双线框字符
    DOUBLE_TOP_LEFT     DB 0C9H  ; ╔
    DOUBLE_TOP_RIGHT    DB 0BBH  ; ╗
    DOUBLE_BOTTOM_LEFT  DB 0C8H  ; ╚
    DOUBLE_BOTTOM_RIGHT DB 0BCH  ; ╝
    DOUBLE_HORIZONTAL   DB 0CDH  ; ═
    DOUBLE_VERTICAL     DB 0BAH  ; ║
    
    ; 尺寸定义
    BOX_WIDTH    EQU 30
    BOX_HEIGHT   EQU 8
    SMALL_WIDTH  EQU 15
    SMALL_HEIGHT EQU 3

.CODE
START:
    ; 初始化数据段
    MOV AX, @DATA
    MOV DS, AX
    
    ; ========== 测试1: 单线框 ==========
    MOV DL, SINGLE_TOP_LEFT
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, SINGLE_HORIZONTAL
SINGLE_TOP:
    CALL PRINT_CHAR
    LOOP SINGLE_TOP
    
    MOV DL, SINGLE_TOP_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 中间行
    MOV BX, BOX_HEIGHT
SINGLE_MIDDLE:
    PUSH BX
    
    MOV DL, SINGLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, ' '
SINGLE_SPACE:
    CALL PRINT_CHAR
    LOOP SINGLE_SPACE
    
    MOV DL, SINGLE_VERTICAL
    CALL PRINT_CHAR
    CALL NEWLINE
    
    POP BX
    DEC BX
    JNZ SINGLE_MIDDLE
    
    ; 底部
    MOV DL, SINGLE_BOTTOM_LEFT
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, SINGLE_HORIZONTAL
SINGLE_BOTTOM:
    CALL PRINT_CHAR
    LOOP SINGLE_BOTTOM
    
    MOV DL, SINGLE_BOTTOM_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    CALL NEWLINE
    
    ; ========== 测试2: 双线框 ==========
    MOV DL, DOUBLE_TOP_LEFT
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, DOUBLE_HORIZONTAL
DOUBLE_TOP:
    CALL PRINT_CHAR
    LOOP DOUBLE_TOP
    
    MOV DL, DOUBLE_TOP_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 中间行
    MOV BX, BOX_HEIGHT
DOUBLE_MIDDLE:
    PUSH BX
    
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, ' '
DOUBLE_SPACE:
    CALL PRINT_CHAR
    LOOP DOUBLE_SPACE
    
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    CALL NEWLINE
    
    POP BX
    DEC BX
    JNZ DOUBLE_MIDDLE
    
    ; 底部
    MOV DL, DOUBLE_BOTTOM_LEFT
    CALL PRINT_CHAR
    
    MOV CX, BOX_WIDTH
    MOV DL, DOUBLE_HORIZONTAL
DOUBLE_BOTTOM:
    CALL PRINT_CHAR
    LOOP DOUBLE_BOTTOM
    
    MOV DL, DOUBLE_BOTTOM_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    CALL NEWLINE
    
    ; ========== 测试3: 嵌套框 ==========
    ; 外框
    MOV DL, DOUBLE_TOP_LEFT
    CALL PRINT_CHAR
    
    MOV CX, SMALL_WIDTH
    MOV DL, DOUBLE_HORIZONTAL
OUTER_TOP:
    CALL PRINT_CHAR
    LOOP OUTER_TOP
    
    MOV DL, DOUBLE_TOP_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 外框中间（包含内框）
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    
    ; 内框顶部
    MOV DL, SINGLE_TOP_LEFT
    CALL PRINT_CHAR
    
    MOV CX, SMALL_WIDTH - 4
    MOV DL, SINGLE_HORIZONTAL
INNER_TOP:
    CALL PRINT_CHAR
    LOOP INNER_TOP
    
    MOV DL, SINGLE_TOP_RIGHT
    CALL PRINT_CHAR
    
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 内框中间行
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV DL, SINGLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV CX, SMALL_WIDTH - 4
    MOV DL, ' '
INNER_SPACE:
    CALL PRINT_CHAR
    LOOP INNER_SPACE
    
    MOV DL, SINGLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 内框底部
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    
    MOV DL, SINGLE_BOTTOM_LEFT
    CALL PRINT_CHAR
    
    MOV CX, SMALL_WIDTH - 4
    MOV DL, SINGLE_HORIZONTAL
INNER_BOTTOM:
    CALL PRINT_CHAR
    LOOP INNER_BOTTOM
    
    MOV DL, SINGLE_BOTTOM_RIGHT
    CALL PRINT_CHAR
    
    MOV DL, DOUBLE_VERTICAL
    CALL PRINT_CHAR
    CALL NEWLINE
    
    ; 外框底部
    MOV DL, DOUBLE_BOTTOM_LEFT
    CALL PRINT_CHAR
    
    MOV CX, SMALL_WIDTH
    MOV DL, DOUBLE_HORIZONTAL
OUTER_BOTTOM:
    CALL PRINT_CHAR
    LOOP OUTER_BOTTOM
    
    MOV DL, DOUBLE_BOTTOM_RIGHT
    CALL PRINT_CHAR
    CALL NEWLINE
    
; ========== 程序结束 ==========
MOV AH, 4CH
INT 21H

; 打印单个字符子程序
PRINT_CHAR:
    PUSH AX
    MOV AH, 02H
    INT 21H
    POP AX
    RET

; 换行子程序
NEWLINE:
    PUSH AX
    PUSH DX
    MOV AH, 02H
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    POP DX
    POP AX
    RET

END START
